import { SessionData } from '@/hooks/useSessionsData';

// Mock data for testing the class attendance functionality
export const mockSessionsData: SessionData[] = [
  {
    trainerId: "1",
    trainerFirstName: "Sarah",
    trainerLastName: "Johnson",
    trainerName: "Sarah Johnson",
    sessionId: "S001",
    sessionName: "Morning Power Cycle",
    capacity: 20,
    checkedInCount: 18,
    lateCancelledCount: 2,
    bookedCount: 20,
    complimentaryCount: 1,
    location: "Kwality House, Kemps Corner",
    date: "2024-01-15",
    dayOfWeek: "Monday",
    time: "07:00",
    totalPaid: 3600,
    nonPaidCount: 1,
    uniqueId: "U001",
    checkedInsWithMemberships: 12,
    checkedInsWithPackages: 4,
    checkedInsWithIntroOffers: 1,
    checkedInsWithSingleClasses: 1,
    classType: "Power Cycle",
    cleanedClass: "Power Cycle",
    fillPercentage: 90,
    revenue: 3600
  },
  {
    trainerId: "2",
    trainerFirstName: "Mike",
    trainerLastName: "Chen",
    trainerName: "Mike Chen",
    sessionId: "S002",
    sessionName: "Evening Barre Flow",
    capacity: 15,
    checkedInCount: 12,
    lateCancelledCount: 1,
    bookedCount: 14,
    complimentaryCount: 0,
    location: "Supreme HQ, Bandra",
    date: "2024-01-15",
    dayOfWeek: "Monday",
    time: "18:30",
    totalPaid: 2400,
    nonPaidCount: 0,
    uniqueId: "U002",
    checkedInsWithMemberships: 8,
    checkedInsWithPackages: 3,
    checkedInsWithIntroOffers: 0,
    checkedInsWithSingleClasses: 1,
    classType: "Barre",
    cleanedClass: "Barre Flow",
    fillPercentage: 80,
    revenue: 2400
  },
  {
    trainerId: "3",
    trainerFirstName: "Emma",
    trainerLastName: "Davis",
    trainerName: "Emma Davis",
    sessionId: "S003",
    sessionName: "Strength & Sculpt",
    capacity: 12,
    checkedInCount: 10,
    lateCancelledCount: 0,
    bookedCount: 11,
    complimentaryCount: 1,
    location: "Kenkere House",
    date: "2024-01-16",
    dayOfWeek: "Tuesday",
    time: "09:00",
    totalPaid: 2000,
    nonPaidCount: 1,
    uniqueId: "U003",
    checkedInsWithMemberships: 6,
    checkedInsWithPackages: 3,
    checkedInsWithIntroOffers: 0,
    checkedInsWithSingleClasses: 1,
    classType: "Strength",
    cleanedClass: "Strength & Sculpt",
    fillPercentage: 83.33,
    revenue: 2000
  },
  {
    trainerId: "1",
    trainerFirstName: "Sarah",
    trainerLastName: "Johnson",
    trainerName: "Sarah Johnson",
    sessionId: "S004",
    sessionName: "Power Cycle Express",
    capacity: 20,
    checkedInCount: 15,
    lateCancelledCount: 3,
    bookedCount: 19,
    complimentaryCount: 2,
    location: "Kwality House, Kemps Corner",
    date: "2024-01-17",
    dayOfWeek: "Wednesday",
    time: "12:00",
    totalPaid: 2700,
    nonPaidCount: 2,
    uniqueId: "U004",
    checkedInsWithMemberships: 10,
    checkedInsWithPackages: 3,
    checkedInsWithIntroOffers: 1,
    checkedInsWithSingleClasses: 1,
    classType: "Power Cycle",
    cleanedClass: "Power Cycle",
    fillPercentage: 75,
    revenue: 2700
  },
  {
    trainerId: "4",
    trainerFirstName: "Alex",
    trainerLastName: "Rodriguez",
    trainerName: "Alex Rodriguez",
    sessionId: "S005",
    sessionName: "Barre Fundamentals",
    capacity: 16,
    checkedInCount: 14,
    lateCancelledCount: 1,
    bookedCount: 16,
    complimentaryCount: 1,
    location: "Supreme HQ, Bandra",
    date: "2024-01-18",
    dayOfWeek: "Thursday",
    time: "17:00",
    totalPaid: 2800,
    nonPaidCount: 1,
    uniqueId: "U005",
    checkedInsWithMemberships: 9,
    checkedInsWithPackages: 4,
    checkedInsWithIntroOffers: 0,
    checkedInsWithSingleClasses: 1,
    classType: "Barre",
    cleanedClass: "Barre Flow",
    fillPercentage: 87.5,
    revenue: 2800
  }
];

export const useMockSessionsData = () => {
  return {
    data: mockSessionsData,
    loading: false,
    error: null,
    refetch: () => Promise.resolve()
  };
};